name: CML Report
on: push
jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: iterative/setup-cml@v1

      - name: deploy
        shell: bash
        env:
          repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml-runner \
          --cloud aws \
          --cloud-region us-west \
          --cloud-type=t2.micro \
          --labels=cml-runner
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate metrics report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# CML Report" > report.md

          echo "## Plots" >> report.md
          dvc plots diff bigrams-experiment workspace \
            --show-vega --targets prc.json > vega.json
          vl2svg vega.json prc.svg
          cml-publish prc.svg --title "Precision & Recall" --md >> report.md

          echo "## Metrics" >> report.md
          echo "### bigrams-experiment → workspace" >> report.md
          dvc metrics diff bigrams-experiment --show-md >> report.md

          cml-send-comment report.md
